# ---
# tasks file for web-nodejs-deploy
- name: download app from S3
  shell: aws --region {{ s3_region }} s3 cp s3://{{ s3_bucket }}/{{ s3_key_path }}/{{ app_version }}.zip /tmp

- name: remove app current dir
  file: name={{ app_dir }} state=absent
  sudo: yes
  sudo_user: root

- name: create app current dir
  file: name={{ app_dir }} state=directory owner=nodejs group=nodejs
  sudo: yes
  sudo_user: root

- name: unzip the app
  unarchive: copy=no src=/tmp/{{ app_version }}.zip dest={{ app_dir }}

- name: stat node_modules dir in app directory
  stat: path={{ app_dir }}/node_modules
  register: node_modules

- name: link to existing node_modules directory if not included in app zip
  file: src={{ app_shared_dir }}/node_modules dest={{ app_dir }}/node_modules state=link
  when: node_modules.stat.exists == False

- name: install npm modules
  shell: sudo su nodejs -c ". /var/nvm/nvm.sh; npm install" chdir={{ app_dir }}
  sudo: yes
  sudo_user: nodejs

- name: restart app
  service: name=node-{{ app }} state=reloaded
  sudo: yes
  sudo_user: root

# -
# - name: Enable service
#   service: name=node-{{app}} enabled=yes
#   notify:
#     - restart web app
