---
# tasks file for web-nodejs-deploy

- include: deploy_from_github.yml
  when: deploy_from == "github"
- include: deploy_from_s3_zip.yml
  when: deploy_from == "s3_zip"

- name: Ensure latest npm modules are installed
  npm: path={{ app_dir }}

- name: Build app
  shell: NODE_ENV={{ env }} node_modules/gulp/bin/gulp.js build
  args:
    chdir: "{{ app_dir }}"

- name: Setup NODE_ENV shell environment variable
  template: src=nodeenv.sh.j2 dest=/etc/profile.d/nodeenv.sh

- name: Setup init script
  template: src=init.sh.j2 dest="/etc/init.d/node-{{app}}" mode=0755

- name: Enable service
  service: name=node-{{app}} enabled=yes
  notify:
    - restart web app


