---
- include: common.yml
- include: nagios.yml
- include: redis.yml
# - include: nagios-config.yml
- include: nodejs.yml
- include: foundationdb.yml
- include: docker.yml
- include: hyperdex.yml
- include: bamboo.yml
