---
# defaults file for web-nodejs

s3_region:   "us-west-2"
s3_bucket:   "intelos"
s3_key_path: "deploy/web"

# general app configuration
env:            "production"
app:            "web"
app_version:    "c3f06eeae425db984d1c7df9d514571c11abfeed"
app_root:       "/var/app"
app_dir:        "{{app_root}}/current"
app_entry:      "server/index.js"
app_port:       80
app_shared_dir: "{{app_root}}/shared"
# src_dir:      "{{shared_dir}}/src"
# current_link: "{{app_root}}/current"
# releases_dir: "{{app_root}}/shared/releases"

# github vars
repo:         "git@github.com:intelos/web.git"
branch:       "master"

# S3 Zip archive vars
# s3_bucket:    "intelos/apps/web/production"
archive:      "web_v1.zip"
