---
galaxy_info:
  author: Mikael Gibert
  description: OrientDB installation  
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - database
  - database:nosql
dependencies: []
