- name: Install latest redis on Ubuntu 14.04
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  sudo_user: root
  vars:
    redis_working_directory: /var/lib/redis
    redis_s3_backup_bucket: nps-devops-test
  tasks:
    - name: ensure apt is up to date
      apt: update_cache=yes

    - name: install python-pycurl (chris-lea/redis-server repo install fails otherwise)
      apt: pkg=python-pycurl state=latest

    - name: install redis repository
      apt_repository: repo='ppa:chris-lea/redis-server' state=present

    - name: ensure apt is up to date with redis
      apt: update_cache=yes

    - name: install redis
      apt: pkg=redis-server state=latest

    - name: install monit
      apt: pkg=monit state=latest

    - name: copy redis.conf.j2 template to servers
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf owner=root mode=644

    - name: setup s3 hourly backup of dump.rdb
      template: src=redis-backup.sh.j2 dest=/etc/cron.hourly/redis-backup.sh owner=root mode=744

    - name: copy sysctl.conf to set vm.overcommit_memory to 1 - fixes dataset dump failures
      copy: src=redis-sysctl.conf dest=/etc/sysctl.conf

    - name: monit config
      copy: src=redis-monit.conf dest=/etc/monit/conf.d/redis.conf

    - name: install pip
      apt: pkg=python-pip state=latest

    - name: install aws cli tools
      pip: name=awscli
