- name: Enable multiverse repositories
  apt_repository: repo="{{item}}" update_cache=no
  register: multiverse_installed
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

- name: Install nodesource key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: copy nodesource.list to /etc/apt/sources.list.d/nodesource.list
  copy: src=nodesource.list dest=/etc/apt/sources.list.d/nodesource.list

- name: Update apt cache after enabling multiverse repos
  apt:
    update_cache: true
  when: multiverse_installed | changed

- name: Install nodejs
  apt: name="nodejs=0.10.25~dfsg2-2ubuntu1" state=present

- name: Install npm
  apt: name=npm state=present

- name: Install zip
  apt: name=zip state=latest

- name: Install ec2-api-tools
  apt: name=ec2-api-tools state=latest

- name: Install JDK 7
  apt: name=openjdk-7-jdk state=latest

- name: Install git
  apt: name=git state=latest

- name: Ensure /opt/node-0.10/bin exists
  file: state=directory path=/opt/node-0.10/bin

- name: Link /usr/bin/node to /usr/bin/nodejs
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Link /opt/node-0.10/bin/node to /usr/bin/nodejs
  file: src=/usr/bin/nodejs dest=/opt/node-0.10/bin/node state=link

- name: Link /opt/node-0.10/bin/npm to /usr/bin/npm
  file: src=/usr/bin/npm dest=/opt/node-0.10/bin/npm state=link

- name: Create bamboo user
  user: name=bamboo createhome=yes

- name: Fetch bamboo agent zip
  shell: wget https://maven.atlassian.com/content/repositories/atlassian-public/com/atlassian/bamboo/atlassian-bamboo-elastic-image/{{bamboo_agent_version}}/atlassian-bamboo-elastic-image-{{bamboo_agent_version}}.zip

- name: Create bamboo directory
  shell: mkdir -p /opt/bamboo-elastic-agent

- name: Unzip bamboo
  shell: unzip -o atlassian-bamboo-elastic-image-{{bamboo_agent_version}}.zip -d /opt/bamboo-elastic-agent

- name: Make bamboo user owner of bamboo agent directory
  shell: chown -R bamboo /opt/bamboo-elastic-agent

- name: Set permissions on bamboon agent directory
  shell: chmod -R u+r+w /opt/bamboo-elastic-agent

- name: Make bamboo user owner of bamboo home directory
  shell: chown -R bamboo:bamboo /home/bamboo

- name: copy bamboo.sh to /etc/profile.d/bamboo.sh
  copy: src=bamboo.sh dest=/etc/profile.d/bamboo.sh

- name: Configure bamboo to start automatically
  lineinfile: dest=/etc/rc.local insertbefore="exit 0" line=". /opt/bamboo-elastic-agent/etc/rc.local"

- name: Setup motd
  shell: cp /opt/bamboo-elastic-agent/etc/motd /etc/motd

- name: Add bamboo version to motd
  shell: echo bamboo-5.8 >> /etc/motd

# - name: Remove files
#   shell: rm -f /root/firstlogin /etc/ssh/ssh_host_dsa_key /etc/ssh/ssh_host_dsa_key.pub /etc/ssh/ssh_host_key /etc/ssh/ssh_host_key.pub /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key.pub /root/.ssh/authorized_keys

- name: Reset first run
  shell: touch /root/firstrun
