- name: Fetch ec2 api tools
  shell: wget http://s3.amazonaws.com/ec2-downloads/ec2-api-tools.zip

- name: Unzip ec2 api tools
  shell: unzip ec2-api-tools.zip

- name: Move ec2 api tools into place
  shell: mv ec2-api-tools-* /opt/ec2-api-tools

- name: Add JDK 8 repository
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: Update apt cache
  apt: update_cache=yes

- name: Install JDK 8
  apt: name=openjdk-8-jdk state=latest

- name: Create bamboo user
  user: name=bamboo createhome=yes

- name: Fetch bamboo agent zip
  shell: wget https://maven.atlassian.com/content/repositories/atlassian-public/com/atlassian/bamboo/atlassian-bamboo-elastic-image/{{bamboo_agent_version}}/atlassian-bamboo-elastic-image-{{bamboo_agent_version}}.zip

- name: Create bamboo directory
  shell: mkdir -p /opt/bamboo-elastic-agent

- name: Unzip bamboo
  shell: unzip -o atlassian-bamboo-elastic-image-{{bamboo_agent_version}}.zip -d /opt/bamboo-elastic-agent

- name: Make bamboo user owner of bamboo agent directory
  shell: chown -R bamboo /opt/bamboo-elastic-agent

- name: Set permissions on bamboon agent directory
  shell: chmod -R u+r+w /opt/bamboo-elastic-agent

- name: Make bamboo user owner of bamboo home directory
  shell: chown -R bamboo:bamboo /home/bamboo

- name: copy bamboo.sh to /etc/profile.d/bamboo.sh
  copy: src=bamboo.sh dest=/etc/profile.d/bamboo.sh

- name: copy rc.local to /root
  copy: src=rc.local dest=/root mode=755

- name: Make sure we're using JDK 8
  lineinfile: dest=/etc/rc.local insertbefore="exit 0" line=". /root/rc.local"

- name: Configure bamboo to start automatically
  lineinfile: dest=/etc/rc.local insertbefore="exit 0" line=". /opt/bamboo-elastic-agent/etc/rc.local"

- name: Setup motd
  shell: cp /opt/bamboo-elastic-agent/etc/motd /etc/motd

- name: Add bamboo version to motd
  shell: echo bamboo-5.8 >> /etc/motd

# - name: Remove files
#   shell: rm -f /root/firstlogin /etc/ssh/ssh_host_dsa_key /etc/ssh/ssh_host_dsa_key.pub /etc/ssh/ssh_host_key /etc/ssh/ssh_host_key.pub /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key.pub /root/.ssh/authorized_keys

- name: Reset first run
  shell: touch /root/firstrun
