- name: update apt cache
  sudo: yes
  apt: update_cache=yes

- name: install node.js repository
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: install nrpe
  sudo: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - nagios-nrpe-server
    - nagios-plugins
    - emacs
    - build-essential
    - python-software-properties
    - python
    - python-pycurl
    - python-pip
    - monit
    - nodejs

- name: ensure local fact directory exists
  sudo: yes
  file: state=directory dest=/etc/ansible/facts.d

- name: copy memory fact script
  sudo: yes
  copy: src=memory.fact dest=/etc/ansible/facts.d/memory.fact mode=750 owner=ubuntu

- name: set allowed hosts so that nrpe daemon accepts connections from nagios servers
  sudo: yes
  template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg
  notify:
  - restart nrpe